site_name: YDNA.me
copyright: Copyright - ydna.me - CC BY-ND 4.0 - 
           <a href="#__consent">Change cookie settings</a>
theme:
  name: material
  logo: img/ydna-me-logo.png
  favicon: img/ydna-me-logo.png
  features:
    - navigation.tabs
    - toc.integrate

plugins:
  - include-markdown


extra:
  consent:
  title: Cookie consent
  description: >- 
      Cookies may be set by the host service (GitHub pages). We don't track anything but they might.
  actions:
      - accept
      - manage


markdown_extensions:
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - attr_list