site_name: YDNA.me
copyright: Copyright - ydna.me - CC BY-ND 4.0 (except images)- 
           <a href="#__consent">Change cookie settings</a>
theme:
  name: material
  custom_dir: override
  logo: img/ydna-me-logo.png
  favicon: img/ydna-me-logo.png
  features:
    - navigation.tabs
    - toc.integrate

plugins:
  - include-markdown
  - git-revision-date-localized:
      enable_creation_date: false
      type: iso_date

extra:
  consent:
  title: Cookie consent
  description: >- 
      Cookies may be set by the host service (GitHub pages). We don't track anything but they might.
  actions:
      - accept
      - manage


markdown_extensions:
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - attr_list


nav:
  - Home: index.md
  - About: about.md
  - Fenland Campaign: fens.md
  - P-L-N Campaign: pln.md
  - Resources: resources.md
  - Disclaimer: disclaimer.md
