site_name: YDNA.me
copyright: Copyright CC BY-ND 4.0 
theme:
  name: material
  logo: img/ydna-me-logo.png
  favicon: img/ydna-me-logo.png
  features:
    - navigation.tabs
    - toc.integrate

plugins:
  - include-markdown


extra:
  consent:
    actions:
      - accept
      - manage